# service 1
services:
  sedcas:

    # Build Docker image
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/deploy/Dockerfile
    
    # Inside the container, use "${WORKING_ROOT}" as the working folder.
    working_dir: ${WORKING_ROOT}

    # start the work flow in container
    command: python ${WORKING_ROOT}/func/liveshow/t1_main.py

    # Restart the container automatically if it crashes
    restart: always

    # Share folders between the real server and the docker container
    volumes:
      ## Mount this folder between the "Docker container" and the "server"
      ## two-way mount: "Docker container" <<-->> "server"
      - ${LOG_DIR_HOST}:${LOG_DIR_CONTAINER}

    # Environment variables passed into the container.
    environment:
      - PYTHONUNBUFFERED=1

# service 2
  dashboard:

    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/deploy/Dockerfile

    working_dir: ${WORKING_ROOT}
    command: python ${WORKING_ROOT}/func/liveshow/t2_main.py --host 0.0.0.0 --port 8050
    restart: always
    volumes:
      - ${LOG_DIR_HOST}:${LOG_DIR_CONTAINER}

    environment:
      - PYTHONUNBUFFERED=1

