# This is the SedCas model input parameters

# Note: the parameters are stored as a Python List or signle variable
# e.g.,
#  params1: 0.1 # this is a signle variable
#  params2:  # this is a list
#    - abc
#    - 0.2
#    - [abc, 0.2]

input_params:
  num_HRU: 2  # Number of hydrological response units (HRU) [-]

  HRUs:  # Description of hydrological response units
    - forest
    - bedrock

  Vwcaps:  # Water storage capacities of HRUs
    - [72, 27]
    - [4]

  ks:  # Residence time parameters for HRUs
    - [94, 235]
    - [23]

  shares:  # Relative share of HRUs to total area
    - 0.56
    - 0.44

  Asnow:  # Albedos for HRUs when covered with snow
    - 0.4
    - 0.65

  Anosnow:  # Albedos for HRUs when not covered with snow
    - 0.15
    - 0.25

  Ele: 1600  # (Mean) catchment elevation [m a.s.l.]

  area: 4.83  # Total catchment area [km2]

  Tsa: 0.6  # Temperature threshold for snow accumulation [°C]

  Tsm: 0.5  # Temperature threshold for snow melt [°C]

  mrate: 0.08  # Melt rate factor [-]

  alphaET: 20.0  # Evapotranspiration parameter [-]

  LStrig: thermal  # Landslide triggering mechanism ['thermal', 'rainfall', 'random']

  Tpr: 7.9  # Precipitation threshold [mm]

  Tsd: 20.0  # Snow-depth threshold [mm SWE]

  Tfreeze: 0  # Temperature threshold for landslide triggered by freezing [°C]

  qdf: 2.40  # Critical discharge for debris flows [mm]

  smax: 0.57  # Max volumetric sediment/water ratio [-]

  smax_nodf: 0.4  # Max possible sediment conc. for bedload [-]

  a: auto  # Scaling parameter for bedload transport
  b: 1.5  # Shape parameter for bedload transport

  Qmin_nondf: auto  # Min discharge for bedload transport initiation

  rhc: 0.12  # Deposition rate hillslope -> channel

  minDF: 2000  # Min debris-flow volume [m3]

  rho_b: 2600  # Bedrock density [kg/m3]

  rho_dry: 2000  # Dry density of stored sediments [kg/m3]

  rho_bulk: 2000  # Density of debris flows [kg/m3]

  shcap: 750000  # Threshold for collapse of hillslope storage [m3]

  ls_xmin: 233  # Minimum landslide volume [m3]

  ls_alpha: 1.69  # Power-law exponent

  ls_cutoff: 3000000  # Max potential landslide volume [m3]

  num_iteration: 100  # Number of stochastic simulations
