# Last Update: 2026-05-19
# Author: QZ
# Note: unit is not added

mcmc_theta_meta:
  lower_bounds: 
    [
      0.1, 10, 10, 
      1, 6, 6, 
    
      1.1,

      0.1, 0.1, 
    
      1, 0.01
    ]
  
  upper_bounds:
    [
      10, 100, 100, 
      144, 1008, 1008, 
    
      2.0,

      1.0, 1.0, 
    
      100, 10
    ]

  theta_names:
    [
     "w_storage_cap0",
     "w_storage_cap1",
     "w_storage_cap2",

     "w_residence_time0",
     "w_residence_time1",
     "w_residence_time2",

     "ls_alpha_v",
      
     "Qdf", "max_s2w",

     "channel_storage_cap", "erosion_k"
    ]

  theta_unit:
    [
     "w_storage_cap0",
     "w_storage_cap1",
     "w_storage_cap2",

     "w_residence_time0",
     "w_residence_time1",
     "w_residence_time2",

     "ls_alpha_v",
      
     "Qdf", "max_s2w",

     "channel_storage_cap", "erosion_k"
    ]

  attrs:
    description: Parameter bounds for calibration
    bounds_space: nature (non-log) sapce
