# This is the SedCas model input parameters

# Note: the parameters are stored as a Python List or signle variable
# e.g.,
#  params1: 0.1 # this is a signle variable
#  params2:  # this is a list
#    - abc
#    - 0.2
#    - [abc, 0.2]


# Model input params
model_input:
  num_iteration:
    name: num_iteration
    value: 100
    attrs:
      unit: None
      description: Number of stochastic simulations
      calibrate: No

# Model config params
model_config:
  # (1) Catchment params
  HRUs:
    name: hru
    value:
      - bedrock
      - forest
    attrs:
      unit: None
      description: Hydrological response units (HRU)
      calibrate: No

  num_HRU:
    name: num_hru
    value: 2
    attrs:
      unit: None
      description: Number of hydrological response units (HRU)
      calibrate: No

  # the origional name is: shares
  area_ratio_HRU: # Relative share of HRUs to total area
    name: ratio_hru
    value: [0.44, 0.56] # for [bedrok, forest]
    attrs:
      unit: ratio
      description: Relative ratio of HRUs to total area
      calibrate: Yes, by remote sensing or DEM data

  num_reservoir:
    name: num_reservoir
    value: 3
    attrs:
      unit: None
      description: Number of reservoirs in HRU, 1 in bedrock HRU (id=0), 2 in forest HRU (top id=1, bottom id=2)
      calibrate: No

  # the original name is: Ele
  c_elevation:
    name: c_elevation
    value: 1600.0
    attrs:
      unit: m (meter)
      description: Mean catchment elevation
      calibrate: Yes, by remote sensing or DEM data

  # area
  c_area:
    name: c_area
    value: 4.83
    attrs:
      unit: km^2
      description: Total catchment area
      calibrate: Yes, by remote sensing or DEM data

  # minDF
  min_df_v:
    name: min_df_v
    value: 2000.0
    attrs:
      unit: m^3
      description: Minium debris-flow volume
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # rho_bulk
  rho_df:
    name: rho_df
    value: 2000.0
    attrs:
      unit: kg/m^3
      description: Density of debris flows
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # rho_b
  rho_bedrock:
    name: rho_br
    value: 2600.0
    attrs:
      unit: kg/m^3
      description: Bedrock density
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # rho_dry
  rho_sediment:
    name: rho_s
    value: 2000.0
    attrs:
      unit: kg/m^3
      description: Dry density of stored sediments
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # shcap
  hillslope_storage_cap:
    name: hillslope_storage_cap
    value: 750000.0
    attrs:
      unit: m^3
      description: Hillslope sediment storage capacity
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # (2) Hydrological params
  initial_w_storage:
    name: initial_w_storage
    value:
      - [4] # for the bedrock
      - [72, 27] # for the forest
    attrs:
      unit: mm
      description: initial water storage in each reservoir
      calibrate: No

  # Vwcaps
  w_storage_cap:
    name: water_storage_cap
    value:
      - [4] # for the bedrock
      - [72, 27] # for the forest
    attrs:
      unit: mm
      description: Water storage capacities of HRUs
      calibrate: Yes, by what ?????

  # ks
  w_residence_time:
    name: water_residence_time
    value:
      - [23] # for the bedrock
      - [94, 235] # for the forest
    attrs:
      unit: h or minutes
      description: Mean residence time in saturated condition
      calibrate: Yes, by what ?????


  # (3) Climate forcing params
  # the original name is: Tsa
  snow_acc_theta:
    name: snow_acc_theta
    value: 0.6
    attrs:
      unit: °C
      description: Temperature threshold for snow accumulation
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # the original name is: Tsm
  snow_melt_theta:
    name: snow_melt_theta
    value: 0.5
    attrs:
      unit: °C
      description: Temperature threshold for snow melt
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # the original name is: mrate
  snow_melt_r:
    name: snow_melt_r
    value: 0.08
    attrs:
      unit: mm °C⁻¹ <time_resolution>⁻¹
      description: Snow melt rate (melt per °C above threshold (e.g., 0.08) per <time_resolution>)
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # the original name is: Asnow
  # ranging from 0 to 1, representing the fraction of incident solar radiation reflected by a surface.
  snow_albedo_y:
    name: with_snow_albedo
    value:
      - 0.65 # for bedrock
      - 0.40 # for forest
    attrs:
      unit: None
      description: Albedo for HRUs when covered with snow
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # the original name is: Anosnow
  # ranging from 0 (low) to 1 (high), representing the fraction of incident solar radiation reflected by a surface.
  snow_albedo_n:
    name: without_snow_albedo
    value:
      - 0.25 # for bedrock
      - 0.15 # for forest
    attrs:
      unit: None
      description: Albedo for HRUs when NOT covered with snow
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # the original name is: alphaET
  et:
    name: evapotranspiration
    value: 20.0
    attrs:
      unit: None
      description: Evapotranspiration efficiency
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # the original name is: cloud_cover_r
  cloud_cover_r:
    name: cloud_cover_r
    value: 1
    attrs:
      unit: None
      description: Cloud cover rate
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # the original name is: cloud_cover_r
  r_humidity:
    name: relative_humidity
    value: 0.8
    attrs:
      unit: None
      description: Relative humidity (higher value -> saturated air)
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739


  # (4) Sediments generator params
  # LStrig:
  ls_trigger_m:
    name: ls_trigger_m
    value: thermal # can be ['thermal', 'rainfall', 'random']
    attrs:
      unit: None
      description: Landslide triggering mechanism
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # Tpr
  ls_trigger_r:
    name: ls_trigger_rainfall
    value: 7.9
    attrs:
      unit: mm / <time_resolution>>
      description: Rainfall threshold for landslide triggered by precipitation
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # Tsd
  ls_trigger_SWE:
    name: ls_trigger_SWE
    value: 20
    attrs:
      unit: mm
      description: SWE threshold for landslide triggered by SWE (snow water equivalent)
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # Tfreeze
  ls_trigger_f:
    name: ls_trigger_freeze
    value: 0
    attrs:
      unit: °C
      description: Temperature threshold for landslide triggered by freezing
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # ls_xmin
  ls_min_v:
    name: ls_min_v
    value: 233
    attrs:
      unit: m^3
      description: Minimum potential landslide volume
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # ls_alpha:
  ls_alpha_v:
    name: ls_alpha_v
    value: 1.69
    attrs:
      unit: None
      description: Power-law exponent for generating landslide
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # ls_cutoff
  ls_max_v:
    name: ls_max_v
    value: 3000000
    attrs:
      unit: m^3
      description: Maximum potential landslide volume
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739


  # (5) Sediments transport params
  # rhc
  h2s_r:
    name: h2s_deposition_rate
    value: 0.12
    attrs:
      unit: None
      description: Sediments deposition rate from hillslope to channel
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  initial_hs_storage:
    name: initial_hs_storage
    value: 119.36
    attrs:
      unit: mm
      description: Initlal hillslope storage, area-normalized sediment thickness
      calibrate: No

  initial_ch_storage:
    name: initial_ch_storage
    value: 0
    attrs:
      unit: mm
      description: Initlal channel storage, area-normalized sediment thickness
      calibrate: No

  Qdf:
    name: discharge_df
    value: 0.6 # 10 minutes -> 0.4 = 2.4 / 6, 1 hour -> 2.4
    attrs:
      unit: mm / <time_resolution>
      description: Discharge threshold for triggering debris flows, if Qs > Qdf, DF could be generated
      calibrate: Yes

  # smax
  max_s2w:
    name: max_s2w
    value: 0.57
    attrs:
      unit: None
      description: Max volumetric sediment to water ratio
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # bedload related
  # smax_nodf
  max_s_c:
    name: max_s_concentration
    value: 0.4
    attrs:
      unit: None
      description: Max possible sediment concentration for bedload
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739

  # b
  bedload_param_b:
    name: bedload_scaling_param_b,
    value: 1.5
    attrs:
      unit: None
      description: Shape parameter for bedload transport, bedload_scaling_param_a will be calculated based on b
      calibrate: Yes, follow https://doi.org/10.1029/2020JF005739


# Model output params
model_output:
  out_hydro_container:
    name: hydrological_output
    value: 1.0
    attrs:
      unit: Check <_create_hydro_dataset>
      description: xr dataset contains time seris data
      calibrate: No

  out_sed_container:
    name: sediments_output
    value: 1.0
    attrs:
      unit: Check <_create_sed_dataset>
      description: xr dataset contains time seris data
      calibrate: No
