# Last modified: 2026-06-11T18:17:59
# Author: QZ


cycle_period:
  name: cycle_period
  value_min: 30 # one month
  value_max: 120 # six monthes
  value_num: 4
  attrs:
    unit: day
    description: storm-drought-cycle
    calibrate: No
    usage: "np.linspace(value_min, value_max, value_num)"

storm2drought_ratio:
  name: storm2drought_ratio
  value_min: 0.05
  value_max: 0.3
  value_num: 6
  attrs:
    unit: none
    description: ratio of storm duration to drought ratio
    calibrate: No
    usage: "np.linspace(value_min, value_max, value_num)"

storm_onset_month:
  name: storm_onset_month
  value_min: 2
  value_max: 10
  value_num: 9 # delta = 1, total 9 cases
  attrs:
    unit: month
    description: month index of the first storm oneset
    calibrate: No
    usage: "np.linspace(value_min, value_max, value_num)"

storm_onset_day:
  name: storm_onset_day
  value_min: 1
  value_max: 15
  value_num: 1 # delta = 15, total 1 cases
  attrs:
    unit: day
    description: day index of the first storm oneset
    calibrate: No
    usage: "np.linspace(value_min, value_max, value_num)"